insert into public.questions (category, type, prompt, options, nsfw_level)
values
  ('connexion', 'text', 'Quel moment recent avec moi t a fait du bien sans que je le sache ?', null, 0),
  ('connexion', 'text', 'Quelle habitude chez nous te rassure le plus ?', null, 0),
  ('connexion', 'text', 'Qu est ce que tu aimerais que je remarque davantage chez toi ?', null, 0),
  ('connexion', 'text', 'A quel moment te sens tu le plus proche de moi ?', null, 0),
  ('connexion', 'text', 'Quel souvenir simple de nous te revient souvent ?', null, 0),
  ('connexion', 'text', 'Qu est ce qui te donne le plus envie de proteger notre relation ?', null, 0),
  ('connexion', 'text', 'Quand est ce que tu te sens le mieux compris par moi ?', null, 0),
  ('connexion', 'text', 'Qu est ce que je fais qui t apaise vraiment ?', null, 0),
  ('connexion', 'scale', 'A quel point te sens tu libre d etre toi meme avec moi ?', null, 0),
  ('connexion', 'scale', 'A quel point te sens tu ecoute en ce moment dans notre relation ?', null, 0),
  ('connexion', 'qcm', 'Quel moment vous reconnecte le plus vite ?', '["Une balade", "Un repas calme", "Un fou rire", "Un long calin"]', 0),
  ('connexion', 'qcm', 'Si on coupe tout pendant une soiree, tu preferes ?', '["Parler longtemps", "Faire une activite", "Sortir", "Rester sous un plaid"]', 0),
  ('projection', 'text', 'Dans un an, qu est ce que tu aimerais qu on ait construit ensemble ?', null, 0),
  ('projection', 'text', 'Quel projet a deux te ferait vraiment vibrer ?', null, 0),
  ('projection', 'text', 'Qu est ce que tu veux proteger a tout prix dans notre futur ?', null, 0),
  ('projection', 'text', 'Quelle version de nous te donne envie de te battre pour elle ?', null, 0),
  ('projection', 'text', 'Quel changement chez nous te ferait le plus de bien ?', null, 0),
  ('projection', 'text', 'Quel rituel aimerais tu qu on installe pour durer ?', null, 0),
  ('projection', 'text', 'Qu est ce que tu veux absolument vivre avec moi au moins une fois ?', null, 0),
  ('projection', 'text', 'Quel genre de maison ou de lieu nous ressemble le plus ?', null, 0),
  ('projection', 'scale', 'A quel point te projettes tu facilement avec moi sur le long terme ?', null, 0),
  ('projection', 'scale', 'A quel point te sens tu aligne avec notre rythme actuel ?', null, 0),
  ('projection', 'qcm', 'Si on se reserve un week-end parfait bientot, tu votes pour ?', '["Ville inconnue", "Cabane au calme", "Road trip", "Maison sans sortir"]', 0),
  ('projection', 'qcm', 'Sur quoi aimerais tu qu on investisse plus d energie a deux ?', '["Temps de qualite", "Aventures", "Communication", "Routine solide"]', 0),
  ('intime', 'text', 'Quel type d attention de ma part te fait le plus te sentir desire ?', null, 1),
  ('intime', 'text', 'Qu est ce que tu n oses pas toujours me demander mais dont tu aurais envie ?', null, 1),
  ('intime', 'text', 'Quand te sens tu le plus attire par moi ?', null, 1),
  ('intime', 'text', 'Qu est ce qui rend un moment entre nous vraiment intense pour toi ?', null, 1),
  ('intime', 'text', 'Quel compliment intime te toucherait le plus venant de moi ?', null, 1),
  ('intime', 'text', 'Quel cadre te met le plus a l aise pour te laisser aller avec moi ?', null, 1),
  ('intime', 'text', 'Qu est ce qui te ferait te sentir encore plus en confiance dans notre intimite ?', null, 1),
  ('intime', 'text', 'Quelle envie douce ou fantaisie legere aimerais tu me partager plus souvent ?', null, 2),
  ('intime', 'scale', 'A quel point te sens tu desire dans notre relation aujourd hui ?', null, 1),
  ('intime', 'scale', 'A quel point arrives tu a exprimer tes envies intimes avec moi ?', null, 1),
  ('intime', 'qcm', 'Qu est ce qui te fait monter le plus vite la tension entre nous ?', '["Le regard", "Les mots", "Le toucher", "L attente"]', 1),
  ('intime', 'qcm', 'Pour une soiree a deux tres proche, tu preferes ?', '["Improviser", "Installer une ambiance", "Se parler d abord", "Laisser la spontaneite faire"]', 1)
on conflict do nothing;
